name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Changed from read to write
      pull-requests: write # Changed from read to write
      issues: write        # Changed from read to write
      id-token: write
      actions: read
      packages: write      # Added for package management
      deployments: write   # Added for deployment access
      statuses: write      # Added for commit status updates
      checks: write        # Added for check runs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Changed from 1 to 0 for full history

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Grant all additional permissions
          additional_permissions: |
            actions: read
            checks: write
            contents: write
            deployments: write
            issues: write
            packages: write
            pull-requests: write
            statuses: write
          
          # Uncomment to use Claude Opus 4 for more complex tasks
          # model: "claude-opus-4-20250514"
          
          # Remove tool restrictions - Claude can run any command
          # allowed_tools is intentional
