name: Claude Code Review

# This workflow automatically reviews PRs using Claude Opus 4 for maximum insight
# Claude performs comprehensive code analysis with full repository access
#
# Permissions explained:
# - contents: write - Allows Claude to suggest file changes if needed
# - pull-requests: write - Enables Claude to comment with review feedback
# - issues: write - Allows Claude to create related issues if critical problems found
# - id-token: write - Required for OIDC authentication with the Claude Code Action  
# - actions: read - Enables Claude to analyze CI test results
#
# Full tool access ensures Claude can:
# - Install dependencies if needed (npm install)
# - Run all test suites and linting
# - Analyze code with any available tools
# - Fetch relevant documentation
# - Make direct code suggestions

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write # Required for GitHub OIDC token authentication
      actions: read # Required for Claude to read CI results
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Specify model - using Claude Opus 4 for maximum capability
          model: "claude-opus-4-20250514"
          
          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please review this pull request following the project standards in CLAUDE.md.
            
            Provide feedback on:
            - Code quality and adherence to Astro framework conventions
            - Proper use of Tailwind CSS for styling
            - TypeScript type safety where applicable
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            
            Run the following checks if applicable:
            - npm install (if dependencies are missing)
            - npm run lint
            - npm run typecheck
            - npm run test
            
            Error Handling:
            - Check if node_modules exists before running commands
            - If any command fails due to missing dependencies, run npm install first
            - Provide clear explanations for any errors encountered
            
            Be constructive and helpful in your feedback.

          # Optional: Use sticky comments to make Claude reuse the same comment on subsequent pushes to the same PR
          # use_sticky_comment: true
          
          # Optional: Customize review based on file types
          # direct_prompt: |
          #   Review this PR focusing on:
          #   - For TypeScript files: Type safety and proper interface usage
          #   - For API endpoints: Security, input validation, and error handling
          #   - For React components: Performance, accessibility, and best practices
          #   - For tests: Coverage, edge cases, and test quality
          
          # Optional: Different prompts for different authors
          # direct_prompt: |
          #   ${{ github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' && 
          #   'Welcome! Please review this PR from a first-time contributor. Be encouraging and provide detailed explanations for any suggestions.' ||
          #   'Please provide a thorough code review focusing on our coding standards and best practices.' }}
          
          # Allow Claude full access to run all necessary commands during review
          allowed_tools: "Bash(*),Read,Grep,Glob,LS,WebFetch,WebSearch,TodoWrite,Edit,MultiEdit,Write"
          
          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')

